<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RailWeaver.Core\RailWeaver.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\data\regions\cordoba.json"
             Link="data\regions\cordoba.json"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\data\regions\cordoba\*.*"
             Link="data\regions\cordoba\%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
